### ISSUE TITLE
main branch fails to build in nightly-2021-08-14 and later

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#1350]
I suspect https://github.com/rust-lang/rust/pull/88032 might fix this.

The symptom is that aarch64 builds fail:
```
  = note: Undefined symbols for architecture arm64:
            "_ring_core_0_17_0_not_released_yet_OPENSSL_armcap_P", referenced from:
                _ring_core_0_17_0_not_released_yet_ChaCha20_ctr32 in libring_core_0_17_0_not_released_yet_.a(chacha-armv8-ios64.o)
                _ring_core_0_17_0_not_released_yet_sha256_block_data_order in libring_core_0_17_0_not_released_yet_.a(sha256-armv8-ios64.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by briansmith** [comment]
PR #1349 works around this by fixing the nightly version in CI to nightly-2021-08-13. We need to revert that PR once we've fix things.

**Comment by briansmith** [comment]
*ring* now builds with the latest Rust Nightly, so the rustc bug must be fixed. PR #1357 reverts the workaround.
