### ISSUE TITLE
Failed to compile on OpenBSD 6.7 aarch64, no fallback option given

### ISSUE THREAD

**Issue by kylegodbold** [briansmith/ring#1054]
All of the #[cfg()] statements in the function fail and leave the body of the function blank, which then returns () instead of a bool.

```

Compiling ring v0.16.15
error[E0308]: mismatched types
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/src/cpu.rs:189:56
    |
189 |         pub fn available(&self, _: super::Features) -> bool {
    |                ---------                               ^^^^ expected `bool`, found`()`
    |                |
    |                implicitly returns `()` as its body has no tail or `return` expression

error: aborting due to previous error
```

**Comment by kylegodbold** [comment]
This same code compiles and runs fine on x86_64 OpenBSD 6.7.

**Comment by briansmith** [comment]
We would need to write feature detection logic for OpenBSD that is analogous to the Linux and Fuchsia feature detection.

We could allow things to compile without doing any feature detection, but that seems like it would be pretty bad since AAarch64 platforms almost always have the instructions to enabled the optimized versions.

**Comment by kylegodbold** [comment]
Allowing it to compile, even if the runtime speed is suboptimal, is much more useful to me. Do you know the location of some of the Linux feature detection code? I don't mind  spending a few hours working on a fix.

**Comment by briansmith** [comment]
> This same code compiles and runs fine on x86_64 OpenBSD 6.7.

The x86_64 and 32-bit x86 code uses the CPUID instruction so it works on every operating system.

in src/cpu.rs, look at `fn linux_setup()`. It uses `getauxval()` to do the feature detection.

**Comment by briansmith** [comment]
I think it's working on openbsd now, though it might not be doing feature detection to enable the fastest implementations.

**Comment by brad0** [comment]
> > This same code compiles and runs fine on x86_64 OpenBSD 6.7.
> 
> The x86_64 and 32-bit x86 code uses the CPUID instruction so it works on every operating system.
> 
> For ARM (including AAarch64), in src/cpu.rs, look at `fn linux_setup()`. It uses `getauxval()` to do the feature detection.

I just happened to run into this Googling for related subject matter, but FreeBSD / OpenBSD uses elf_aux_info() which is analogous to getauxval() and uses the same hardware feature flags for hardware detection on ARM, PPC, RISC-V.
