### ISSUE TITLE
Regression: ring does not cross-compile to aarch64-unknown-linux-gnu-gcc in the manylinux2014-cross image anymore

### ISSUE THREAD

**Issue by orlp** [briansmith/ring#1789]
It used to work fine in ring 0.16.20, but fails in 0.17.x (not sure where the first failure is).

A failing run due to ring 0.17.x is here: https://github.com/orlp/polars/actions/runs/6731785254/job/18297168161.

A successful run that only includes ring 0.16.20 but not 0.17.x is here: https://github.com/pola-rs/polars/actions/runs/6677388345/job/18147372052.

We now get `error: #error "ARM assembler must define __ARM_ARCH"` error messages.

**Comment by okynos** [comment]
Same issue here. Struggling with my own code...

I can reproduce the error in a `centos:7` ARM container.

Short trace:
```
warning: In file included from /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.17.5/pregenerated/aesv8-armx-linux64.S:4:0:
warning: include/ring-core/asm_base.h:73:2: error: #error "ARM assembler must define __ARM_ARCH"
warning:  #error "ARM assembler must define __ARM_ARCH"
warning:   ^
warning: In file included from /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.17.5/pregenerated/aesv8-armx-linux64.S:7:0:
warning: include/ring-core/arm_arch.h:82:2: error: #error "ARM assembler must define __ARM_ARCH"
warning:  #error "ARM assembler must define __ARM_ARCH"
warning:   ^

error: failed to run custom build command for `ring v0.17.5`
```

**Comment by briansmith** [comment]
Closing as a duplicate of #1728. Upsteam BoringSSL supports compilers up to 5 years old. Sometimes we can tweak things to avoid depending on new features, but this is one of the few things that seem unreasonably difficult to try to support when upstream doesn't support it.

See https://github.com/briansmith/ring/issues/1728#issuecomment-1758180655 for a workaround; basically upgrading to a newer manylinux.

**Comment by okynos** [comment]
@briansmith what about `centos:7` case? it is still supported and lots of servers still using it...

**Comment by briansmith** [comment]
> @briansmith what about centos:7 case? it is still supported and lots of servers still using it..

On Aarch64?

> Do you mean the only way to workaround it is to swap to CentOS 8 or CentOS 9?

I think the problem is that GCC 4.8 on CentOS doesn't conform to the ARM C compiler extensions (ACLE]. So you maybe you could use a newer GCC or otherwise try Clang.
