### ISSUE TITLE
cant build with vs2017 15.8.0 preview5 on windows10 17730

### ISSUE THREAD

**Issue by gettf** [briansmith/ring#686]
use vs2017 native x64 cmd
cargo build --release
 Compiling ring v0.13.2
error: failed to run custom build command for `ring v0.13.2 (file:///f:/rlib/ring)`
process didn't exit successfully: `f:\rlib\ring\target\release\build\ring-4a04381dc42de574\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'execution failed', build.rs:613:9

rust env
nightly-x86_64-pc-windows-msvc (default)
rustc 1.30.0-nightly (73c78734b 2018-08-05)
try stable  rustc 1.28.0 also failed

**Comment by ThatNerdyPikachu** [comment]
can confirm

**Comment by antekone** [comment]
This happens on my box:

```
running "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "include" "/GS" "/Gy" "/EHsc" "/GR-" "/Zc:wchar_t" "/Zc:forScope" "/Zc:inline" "/Zc:rvalueCast" "/sdl" "/Wall" "/WX" "/wd4127" "/wd4464" "/wd4514" "/wd4710" "/wd4711" "/wd4820" "/Od" "/RTCsu" "/W4" "-c" "/FoD:\\msys64\\home\\antek\\dev\\rust\\cdabackend\\target\\debug\\build\\ring-d6426aa3b9d21a5c\\out\\exponentiation.obj" "crypto/bn/exponentiation.c"
ecp_nistz256.c
exponentiation.c
c:\users\antek\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\crypto\limbs\limbs.inl(128) : error C2220: warning treated as error - no 'object' file generated
c:\users\antek\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\crypto\limbs\limbs.inl(128) : warning C5045: Compiler will insert Spectre mitigation for memory load if /Qspectre switch specified
c:\users\antek\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\crypto\limbs\limbs.inl(127) : note: index 'i' range checked by comparison on this line
c:\users\antek\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\crypto\limbs\limbs.inl(128) : note: feeds call on this line
```

**Comment by SteelPh0enix** [comment]
same here, nightly 1.30.0

**Comment by adubois** [comment]
I think same here with v0.11 nightly (trying to use Rocket 0.3.17).

additional log extract that may be useful.
```
running "D:\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "include" "/GS" "/Gy" "/EHsc" "/GR-" "/Zc:wchar_t" "/Zc:forScope" "/Zc:inline" "/Zc:rvalueCast" "/sdl" "/Wall" "/WX" "/wd4127" "/wd4464" "/wd4514" "/wd4710" "/wd4711" "/wd4820" "/Od" "/RTCsu" "/W4" "-c" "/FoD:\\Projects\\rust\\rust-contacts\\target\\debug\\build\\ring-e039111ccd603203\\out\\gfp_p384.obj" "crypto/ec/gfp_p384.c"
generic.c
gfp_p384.c
constant_time_test.c
ecp_nistz256.c
c:\users\alex\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\crypto\limbs\limbs.inl(128) : error C2220: warning treated as error - no 'object' file generated
c:\users\alex\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\crypto\limbs\limbs.inl(128) : warning C5045: Compiler will insert Spectre mitigation for memory load if /Qspectre switch specified
c:\users\alex\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\crypto\limbs\limbs.inl(127) : note: index 'i' range checked by comparison on this line
c:\users\alex\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\crypto\limbs\limbs.inl(128) : note: feeds call on this line

```
I am just playing with rust, so I hope my contrib saves you time rather than waste it.
Could be that the C chain has enforced /WX /W4 to ensure lib owner assess Spectre impact.

Link to Microsoft doc on [C2220](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2220?view=vs-2017)

**Comment by adubois** [comment]
Apologies, the problem is that the rocket dependency calculation point to v0.11 also I would have expected to have a feature cascade to choose security or performance in regards to Spectre. I'll raise it with Rocket or cookie-rs.

**Comment by briansmith** [comment]
Please try *ring* v0.13.5 and report back. I verified that this builds with Visual Studio 2017 15.9.1.

**Comment by briansmith** [comment]
Closing this since it seems to be fixed for me.
