### ISSUE TITLE
Work around lack of stdalign.h on OpenBSD

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#294]
As reported in #287, compilation fails with OpenBSD's GCC 4.8 because it lacks stdalign.h:

```
--- stderr
In file included from crypto/aes/aes.c:55:0:
crypto/aes/../internal.h:136:22: fatal error: stdalign.h: No such file or directory
 #include <stdalign.h>
                      ^
compilation terminated.
gmake: *** [mk/bottom_of_makefile.mk:37: /home/oherrala/rust/ring/target/debug/build/ring-3175a83ad649b58d/out/obj/crypto/aes/aes.o] Error 1
In file included from crypto/bn/internal.h:135:0,
                 from crypto/bn/add.c:64:
crypto/bn/../internal.h:136:22: fatal error: stdalign.h: No such file or directory
 #include <stdalign.h>
                      ^
gmake: *** Waiting for unfinished jobs....
compilation terminated.
```

In crypto/internal.h:

``` c
#if defined(_MSC_VER)
#pragma warning(push, 3)
#include <intrin.h>
#pragma warning(pop)
#if !defined(__cplusplus)
#define alignas(x) __declspec(align(x))
#define alignof __alignof
#endif
#elif !defined(__clang__) && defined(__GNUC__) && __GNUC__ == 4 && \
      __GNUC_MINOR__ <= 6
#define alignas(x) __attribute__((aligned (x)))
#define alignof __alignof__
#else
#include <stdalign.h>
#endif
```

It seems like we need to extend the support added for GCC 4.6 to handle the OpenBSD case. Ideally `__has_include` would be used, but that only works in GCC 5.1 and later. So, maybe the solution is to just add an OpenBSD-specific thing to the `#elif`.

**Comment by briansmith** [comment]
Closing this based on https://www.phoronix.com/scan.php?page=news_item&px=OpenBSD-Adds-LLVM-To-Base, in particular “OpenBSD currently makes use of GCC 4.2.1, the latest series of the GNU Compiler Collection being under the GPLv2”. We don't support such ancient versions of GCC, so people should just use Clang on OpenBSD. LMK if this is problematic.
